# config/mycobot_joy_teleop.yaml
teleop_twist_joy:
  ros__parameters:
    require_enable_button: true          # Require a deadman button held to move [oai_citation:8‡docs.ros.org](https://docs.ros.org/en/iron/p/teleop_twist_joy/standard_docs/README.html#ros2-teleop-twist-joy%23:~:text=)
    enable_button: 4                    # e.g. Xbox: LB as enable (index 4)
    enable_turbo_button: 5              # e.g. Xbox: RB as turbo for faster speed (index 5)
    axis_linear:
      x: 1   # left stick vertical -> X translation
      y: 0   # left stick horizontal -> Y translation
      z: 4   # right stick vertical -> Z translation (e.g. axis 4 on Xbox)
    axis_angular:
      yaw: 3    # right stick horizontal -> yaw rotation
      pitch: -1 # (unused)
      roll:  -1 # (unused)
    scale_linear:
      x: 0.01   # 1% of full stick = 0.01 (m/s) normal speed
      y: 0.01
      z: 0.01
    scale_linear_turbo:
      x: 0.03   # higher speed when turbo button held
      y: 0.03
      z: 0.03
    scale_angular:
      yaw: 0.5   # ~0.5 rad/s normal
    scale_angular_turbo:
      yaw: 1.0   # ~1.0 rad/s with turbo
